# Generated by Django 3.2.3 on 2021-06-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
